version: "3.8"

services:
  frontend:
    container_name: csds_frontend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always